18-week/2-day/forms-and-bp/app/forms/auth.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired, Length


class LoginForm(FlaskForm):
    username = StringField("Username: ", validators=[InputRequired(), Length(5)])
    password = StringField("Password: ")
    submit = SubmitField("Submit")

18-week/2-day/forms-and-bp/app/__init__.py
user = {}
from flask import Flask, render_template
from app.config import Config
from .routes import auth_routes


app = Flask(__name__)

app.config.from_object(Config)


@app.route("/")
def index():
    return render_template("index.html", message="my message", user=user)

@app.route("/names")
def names():
    return render_template("names.html", message="my message", user=user)


app.register_blueprint(auth_routes)

18-week/2-day/forms-and-bp/app/routes/__init__.py
from .auth import auth_routes

18-week/2-day/forms-and-bp/app/routes/auth.py
from flask import render_template, request, redirect, url_for, Blueprint
from app import user
from app.forms.auth import LoginForm

auth_routes = Blueprint("auth", __name__, url_prefix="/auth")

@auth_routes.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            username = request.form["username"]
            password = request.form["password"]
            print("CREDENTIALS: ", username, password)
            error = None
            user["username"] = username
            if error is None: # fake
                return redirect(url_for("index"))

    return render_template("login.html", form=form)

18-week/2-day/forms-and-bp/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Form and Blueprints</title>
  </head>
  <body>
{%include 'navigation.html'%}

    {%block header%}{%endblock%}

    {%block content%}{%endblock%}

  </body>
</html>

18-week/2-day/forms-and-bp/app/templates/index.html
{% extends 'base.html' %}

{%block content%}
<p>this is html i want to have </p>
{{message}}
{%include "new.html"%}
<p>wrapped around new.html</p>

{%endblock%}
{%block header%}
{% if user %}
<h1>Hello {{user.username}}!</h1>
{% else %}
<h1>Hello World!!!!</h1>
{% endif %}
{%endblock%}

18-week/2-day/forms-and-bp/app/templates/login.html
{% extends 'base.html' %} {% block header %}
<h1>{% block title %}Log In{% endblock %}</h1>
{% endblock %} {% block content %} {% if error %}
<p>{{error['error']}}</p>
{% endif %}
<form method="post">
  {{form.csrf_token}}
  <p>{{form.username.label}} {{form.username}}</p>
  <p>{{form.password.label}} {{form.password}}</p>
  <p>{{form.submit}}</p>
</form>
{% endblock %}

18-week/2-day/forms-and-bp/app/templates/names.html
{% extends 'base.html' %}


{%block header%}
<h1>Names Header</h1>
{%endblock%}

{%block content%}
<p>will</p>
<p>bri</p>
{#
    <!-- {%block name%} -->
#}


{%endblock%}

18-week/2-day/forms-and-bp/app/templates/navigation.html
<nav>
  <a href="/">Home</a>
  <a href="{{ url_for('auth.login') }}">Log In</a>
  <a href="{{ url_for('index') }}">index</a>
  <a href="{{ url_for('names') }}">Names</a>
</nav>

18-week/2-day/forms-and-bp/app/templates/new.html
<p style='color: red'>I'm was included from new.html!</p>