18-week/2-day/lecture-code/app/forms/__init__.py
from .post import PostForm

18-week/2-day/lecture-code/app/forms/post.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import InputRequired, Length, URL

from ..posts import users

user_choices = [user["name"] for user in users]

class PostForm(FlaskForm):
    author = SelectField("Author: ", choices=user_choices)
    caption = StringField("Caption: ", validators=[InputRequired(), Length(max=2000)])
    image = StringField("Image URL: ", validators=[InputRequired(), URL()])
    submit = SubmitField("Submit")

18-week/2-day/lecture-code/app/__init__.py
from flask import Flask, render_template, redirect, url_for
from app.config import Config
from .posts import posts, users

from .routes import post_router, user_router


app = Flask(__name__)


app.config.from_object(Config)

app.register_blueprint(post_router)
app.register_blueprint(user_router)


@app.route("/", methods=["GET"])
def index():
    return render_template("index.html")

18-week/2-day/lecture-code/app/routes/__init__.py
from .posts import post_router
from .users import user_router

18-week/2-day/lecture-code/app/routes/posts.py
from flask import Blueprint, render_template, redirect, url_for
from app.posts import posts, random_date_2023
from app.forms import PostForm


post_router = Blueprint("posts", __name__, url_prefix="/posts")


@post_router.route("")
def all_posts():
    return render_template("posts.html", posts=posts, page_type="posts")


@post_router.route("/<int:id>/delete", methods =["GET"])
def delete_post(id):
    post_to_delete = [post for post in posts if post["id"] == id][0]
    posts.remove(post_to_delete)
    return redirect(url_for("posts.all_posts"), 302)

@post_router.route("/<int:id>")
def get_single_post(id):
    post = [post for post in posts if post["id"] == id]
    return render_template("posts.html", posts=post, post_type="post")

@post_router.route("/new", methods=["GET", "POST"])
def create_new_post():
    form = PostForm()

    if form.validate_on_submit():
        new_post = {}
        new_post["id"] = posts[-1]["id"] + 1
        new_post["author"] = form.data["author"]
        new_post["caption"] = form.data["caption"]
        new_post["image"] = form.data["image"]
        new_post["date"] = random_date_2023()
        new_post["likes"] = 0
        posts.append(new_post)
        return redirect("/posts")
    if form.errors:
        # print(form.errors)
        pass
    return render_template("new-post.html", form=form)

@post_router.route("/<int:id>/update")
def update_post_form(id):
    form = PostForm()
    post_to_update = [post for post in posts if post["id"] == id][0]
    form.process(data=post_to_update)
    return render_template("new-post.html", id=id, form=form)

@post_router.route("/<int:id>/update", methods=["POST"])
def update_post(id):
    form = PostForm()

    if form.validate_on_submit():
        new_post = {
            "id": id,
            "author": form.data["author"],
            "caption": form.data["caption"],
            "image": form.data["image"],
            "date": random_date_2023(),
            "likes": 0,
        }
        for idx, post in enumerate(posts):
            if post["id"] == id:
                posts[idx] = new_post
        if form.errors:
            return render_template("new-post.html", form=form)

        return redirect(f"/posts/{id}")

18-week/2-day/lecture-code/app/routes/users.py
from flask import Blueprint, render_template, redirect
from ..posts import posts, users


user_router = Blueprint("users", __name__, url_prefix="/users")

@user_router.route("/<int:id>/posts")
def get_single_users_posts(id):
    user = users[id-1]
    user_posts = [post for post in posts if post["author"] == user["name"]]
    return render_template("posts.html", posts=user_posts, page_type="user")

18-week/2-day/lecture-code/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %}Pipstagram{% endblock %}
        </title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="css/style.css" rel="stylesheet" />
        <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}" />
        <link rel="icon" href="{{ url_for('static', filename='favicon32.png') }}" />
    </head>
    <body>
        {% include "navbar.html" %}
        {% block posts %}{% endblock %}
    </body>
</html>

18-week/2-day/lecture-code/app/templates/footer.html
<footer class="footer">
  <span class="footer-text">Created by Brad Simpson ©2023</span>
</footer>

18-week/2-day/lecture-code/app/templates/index.html
{% extends "base.html" %}
{% block posts %}
    <div class="splash-container">
        <div>
            <h1 class="splash-title">Pipstagram</h1>
            <img class="splash-logo" src="/static/favicon32.png" alt="cat-logo" />
            <p class="splash-detail">The dog with so much to talk about, he needs his own social media site!</p>
        </div>
        <a href="/posts" class="button-link">Enter</a>
    </div>
{% endblock %}

18-week/2-day/lecture-code/app/templates/navbar.html
<div class="nav-container">
    <div class="nav-logo-container">
      <img class="nav-logo" src="/static/favicon32.png" alt="cat-logo" />
    <h1 class="nav-title">
        <a href="/">
          Pipstagram
        </a>
  </h1>
    </div>
  <div><a href="{{url_for('posts.all_posts')}}">Feed</a>
  </div>
  <div>
    <a href="{{url_for('posts.create_new_post')}}">New Post</a>
  </div>

  <div>
  <a href="/users/1/posts">Pip's Posts</a>
  <a href="/users/2/posts">Luna's Posts</a>
  <a href="/users/3/posts">Loki's Posts</a>
  </div>
</div>

18-week/2-day/lecture-code/app/templates/new-post.html
{% extends "base.html" %}

{% block posts %}
{% if id %}
<form class="post-form" method="post" action="/posts/{{id}}/update">
  <h2>Update Post {{id}}</h2>
  {% else %}
<form class="post-form" method="post" action="/posts/new">
  <h2>Create New Post</h2>
{% endif %}
  {{form.csrf_token}}
    <p>
  {{form.errors.author}}
  {{form.author.label}}{{form.author}}
    </p>
    <p>

  {{form.errors.caption}}
  {{form.caption.label}}{{form.caption}}
    </p>
    <p>

  {% for error in form.errors.image %}
  {{error}}
  {% endfor %}
  {{form.image.label}}{{form.image}}
    </p>
  {{form.submit}}
</form>
  {% endblock %}

18-week/2-day/lecture-code/app/templates/posts.html
<link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}" />
<link rel="icon" href="{{ url_for('static', filename='favicon32.png') }}" />
{% extends "base.html" %}
{% block title %}
    {% if page_type == "posts" %}
        All Posts
    {% elif page_type == "user" %}
        {{ posts[0].author }}'s Posts
    {% else %}
        Post {{ posts[0].id }}
    {% endif %}
{% endblock %}
{% block posts %}
    <div class="feed-container">
        {% for post in posts %}
            <div class="post-container">
                <div class="post-box">
                    <div class="post-author">
                        {% if post.author == "Pip" %}
                            <h2 style="color: red">{{ post.author }}</h2>
                        {% elif post.author == "Loki" %}
                            <h2 style="color: blue">{{ post.author }}</h2>
                        {% else %}
                            <h2 style="color: green">{{ post.author }}</h2>
                        {% endif %}
                    </div>
                    <h3>{{ post.date.strftime("%B %-d, %Y at %-I:%M %p") }}</h3>
                </div>
                <div>
                    <a href="/posts/{{ post.id }}">
                        <img class="post-image" src="{{ post.image }}" />
                    </a>
                    <p class="post-text">{{ post.caption }}</p>
                    <div class="post-operations">
                        <a href="/posts/{{ post.id }}/delete">Delete Post</a>
                        <a href="/posts/{{ post.id }}/update">Update Post</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% include "footer.html" %}

18-week/2-day/lecture-code/app/templates/test.html
<form>
  {% for field in form %}
  {% if field.label = "test" %}
  {% endif %}
  {% endfor %}
</form>