18-week/practices/python-order-up/app/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()


class Employee(db.Model, UserMixin):
    __tablename__ = "employees"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    employee_number = db.Column(db.Integer, nullable=False, unique=True)
    hashed_password = db.Column(db.String(255), nullable=False)

    orders = db.relationship("Order", back_populates="employee")

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


class Menu(db.Model):
    __tablename__ = "menus"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)

    items = db.relationship("MenuItem", back_populates="menu")


class MenuItem(db.Model):
    __tablename__ = "menu_items"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)
    price = db.Column(db.Float, nullable=False)
    menu_id = db.Column(db.Integer, db.ForeignKey("menus.id"))
    menu_type_id = db.Column(db.Integer, db.ForeignKey("menu_item_types.id"))

    menu = db.relationship("Menu", back_populates="items")
    type = db.relationship("MenuItemType")


class MenuItemType(db.Model):
    __tablename__ = "menu_item_types"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)


class Order(db.Model):
    __tablename__ = "orders"

    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer,
                            db.ForeignKey("employees.id"),
                            nullable=False)
    table_id = db.Column(db.Integer,
                         db.ForeignKey("tables.id"),
                         nullable=False)
    finished = db.Column(db.Boolean, nullable=False)

    employee = db.relationship("Employee", back_populates="orders")
    table = db.relationship("Table", back_populates="orders")
    details = db.relationship("OrderDetail", back_populates="order")

    @property
    def total(self):
        return sum([detail.menu_item.price for detail in self.details])


class OrderDetail(db.Model):
    __tablename__ = "order_details"

    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer,
                         db.ForeignKey("orders.id"),
                         nullable=False)
    menu_item_id = db.Column(db.Integer,
                             db.ForeignKey("menu_items.id"),
                             nullable=False)

    order = db.relationship("Order", back_populates="details")
    menu_item = db.relationship("MenuItem")


class Table(db.Model):
    __tablename__ = "tables"

    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.Integer, nullable=False)
    capacity = db.Column(db.Integer, nullable=False)

    orders = db.relationship("Order", back_populates="table")

18-week/practices/python-order-up/app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import (
    PasswordField, SelectField, SelectMultipleField, StringField, SubmitField
)
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    employee_number = StringField("Employee number", [DataRequired()])
    password = PasswordField("Password", [DataRequired()])
    submit = SubmitField("Login")


class MenuItemAssignmentForm(FlaskForm):
    menu_item_ids = SelectMultipleField("Menu items", coerce=int)


class TableAssignmentForm(FlaskForm):
    assign = SubmitField("Assign")
    employees = SelectField("Servers", [DataRequired()], coerce=int)
    tables = SelectField("Tables", [DataRequired()], coerce=int)

18-week/practices/python-order-up/app/__init__.py
from flask import Flask
from flask_login import LoginManager
from .config import Configuration
from .models import db, Employee
from .routes import orders, session

app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(orders.bp)
app.register_blueprint(session.bp)
db.init_app(app)
login = LoginManager(app)
login.login_view = "session.login"


@login.user_loader
def load_user(id):
    return Employee.query.get(int(id))

18-week/practices/python-order-up/app/routes/orders.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_required
from ..models import (
    db, Employee, MenuItem, MenuItemType, Order, OrderDetail, Table
)
from ..forms import MenuItemAssignmentForm, TableAssignmentForm
from sqlalchemy.orm import joinedload

bp = Blueprint("orders", __name__, url_prefix="")


@bp.route("/orders/<int:id>/items", methods=["POST"])
@login_required
def add_to_order(id):
    form = MenuItemAssignmentForm()
    form.menu_item_ids.choices = [(item.id, '')
                                  for item in MenuItem.query.all()]
    from pprint import pprint
    pprint(form.menu_item_ids.choices)
    if form.validate_on_submit():
        order = Order.query.get(id)
        for menu_item_id in form.menu_item_ids.data:
            detail = OrderDetail(order=order, menu_item_id=menu_item_id)
            db.session.add(detail)
        db.session.commit()
    return redirect(url_for('.index'))


@bp.route("/assignments", methods=["POST"])
@login_required
def assign():
    form = TableAssignmentForm()
    open_tables, servers = open_tables_and_servers()
    form.tables.choices = [(t.id, f"Table {t.number}") for t in open_tables]
    form.employees.choices = [(e.id, e.name) for e in servers]
    if form.validate_on_submit():
        order = Order(
            employee_id=form.employees.data,
            table_id=form.tables.data,
            finished=False
        )
        db.session.add(order)
        db.session.commit()
    return redirect(url_for('.index'))


@bp.route("/finalization/<int:id>", methods=["POST"])
@login_required
def close(id):
    order = Order.query.get(id)
    order.finished = True
    db.session.commit()
    return redirect(url_for('.index'))


@bp.route("/")
@login_required
def index():
    taf = TableAssignmentForm()
    open_tables, servers = open_tables_and_servers()
    taf.tables.choices = [(t.id, f"Table {t.number}") for t in open_tables]
    taf.employees.choices = [(e.id, e.name) for e in servers]

    open_orders = Order.query.filter(
        Order.finished == False and Order.employee_id == current_user.id
    ).options(joinedload(Order.table)).options(joinedload(Order.details, OrderDetail.menu_item))

    foods = MenuItem.query.join(MenuItemType).order_by(MenuItemType.name, MenuItem.name).options(joinedload(MenuItem.type))
    foods_by_type = {}
    for food in foods:
        if food.type.name not in foods_by_type:
            foods_by_type[food.type.name] = []
        foods_by_type[food.type.name].append(food)

    data = {'taf': taf, 'orders': open_orders, 'foods_by_type': foods_by_type}
    return render_template("orders.html", **data)


def open_tables_and_servers():
    tables = Table.query.order_by(Table.number)
    open_orders = Order.query.filter(Order.finished == False)
    busy_table_ids = [order.table_id for order in open_orders]
    open_tables = [table for table in tables if table.id not in busy_table_ids]
    servers = Employee.query.all()
    return open_tables, servers

18-week/practices/python-order-up/app/routes/session.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user
from ..forms import LoginForm
from ..models import Employee

bp = Blueprint("session", __name__, url_prefix="/session")


@bp.route("/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("orders.index"))
    form = LoginForm()
    from pprint import pprint
    pprint(form.data)
    if form.validate_on_submit():
        n = form.employee_number.data
        employee = Employee.query.filter(Employee.employee_number == n).first()
        if not employee or not employee.check_password(form.password.data):
            return redirect(url_for(".login"))
        login_user(employee)
        return redirect(url_for("orders.index"))
    return render_template("login.html", form=form)


@bp.route('/logout', methods=["POST"])
def logout():
    logout_user()
    return redirect(url_for('.login'))

18-week/practices/python-order-up/app/templates/base.html
<html>
  <head>
    <link rel="stylesheet" href="/static/order-up.css">
    {% if title %}
      <title>{{ title }} - Order Up!</title>
    {% else %}
      <title>Welcome to Order Up!</title>
    {% endif %}
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

18-week/practices/python-order-up/app/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="{{ url_for('.login') }}">
  {{ form.csrf_token }}
  <div>
    {{ form.employee_number.label }} {{ form.employee_number }}

    {% if form.employee_number.errors %}
      <ul>
        {% for error in form.employee_number.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
  <div>
    {{ form.password.label }} {{ form.password }}

    {% if form.employee_number.errors %}
      <ul>
        {% for error in form.employee_number.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
  <div>{{ form.submit }}</div>
</form>
{% endblock %}

18-week/practices/python-order-up/app/templates/orders.html
{% extends "base.html" %}

{% block content %}
<div id="workspace">
  <header class="actions-header">
    <form class="assignment-form" method="post" action="{{ url_for('.assign') }}">
      {{ taf.csrf_token }}
      <div class="assignment-form-title">Assign Table</div>
      <div class="assignment-form-select">{{ taf.tables }}</div>
      <div class="assignment-form-select">{{ taf.employees }}</div>
      <div class="assignment-form-submit">{{ taf.assign(class="button assign") }}</div>
    </form>
    <form class="logout-form" method="post" action="{{ url_for('session.logout') }}">
      <button class="logout">Logout</button>
    </form>
  </header>
  <main>
    <table class="orders-table">
      <thead>
        <tr>
          <th colspan="4" class="table-title">Your Open Orders</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
          <tr class="order-row">
            <td>Table {{ order.table.number }}</td>
            <td>{{ "${:,.2f}".format(order.total) }}</td>
            <td class="order-action-cell">
              <form method="post" action="{{ url_for('.close', id=order.id) }}">
                {{ taf.csrf_token }}
                <button class="micro">Close table</button>
              </form>
            </td>
            <td class="order-action-cell">
              <button class="micro" form="food-list" formaction="{{ url_for('.add_to_order', id=order.id) }}">Add to order</button>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <aside class="food-list">
      <form id="food-list" method="post">
        {% for type, foods in foods_by_type.items() %}
          {{ taf.csrf_token }}
          <section class="food-type-group">
            <header class="food-type-header">{{ type }}</header>
            <div class="foods">
              {% for food in foods %}
                <div class="food-choice">
                  <input type="checkbox" name="menu_item_ids" value="{{ food.id }}"> {{ food.name }}
                </div>
              {% endfor %}
            </div>
          </section>
        {% endfor %}
      </form>
    </aside>
  </main>
</div>
{% endblock %}